### ISSUE TITLE
illegal memory access during parallel forward training

### ISSUE THREAD

**Issue by CsRic** [STAR-Laboratory/Accelerating-RecSys-Training#3]
Hi, I encountered crash when training on criteo_kaggle dataset.
I followed instructions for Pre-processing, FAE Profiling and Running FAE. The first Mixed forward training ran successful, but this is what I got when the parallel forward training part begin:
![Snipaste_2022-08-17_19-23-05](https://user-images.githubusercontent.com/59389055/185331225-71ad801b-b97c-4858-b0e5-12d489f94d81.png)

environment: 
python=3.7.13, torch=1.3.1, cudatoolkit=10.1
CPU: AMD EPYC 7543 32-Core
GPU: 8 * NVIDIA A100

**Comment by Wangzesonga** [comment]
> Hi, I encountered crash when training on criteo_kaggle dataset. I followed instructions for Pre-processing, FAE Profiling and Running FAE. The first Mixed forward training ran successful, but this is what I got when the parallel forward training part begin: ![Snipaste_2022-08-17_19-23-05](https://user-images.githubusercontent.com/59389055/185331225-71ad801b-b97c-4858-b0e5-12d489f94d81.png)
> 
> environment: python=3.7.13, torch=1.3.1, cudatoolkit=10.1 CPU: AMD EPYC 7543 32-Core GPU: 8 * NVIDIA A100

I meet the same problem, have you find a way to solute it?

**Comment by madnan92** [comment]
Hi @Wangzesonga 
We have fixed the indices of hot embeddings.
Due to an unknown index of hot embedding, CUDA was giving illegal memory access.
Please re-run the profiling and then run dlrm_fae with updated profiled hot/cold inputs and hot_emb_dict.

**Comment by Wangzesonga** [comment]
> Hi @Wangzesonga We have fixed the indices of hot embeddings. Due to an unknown index of hot embedding, CUDA was giving illegal memory access. Please re-run the profiling and then run dlrm_fae with updated profiled hot/cold inputs and hot_emb_dict.

Thank you for your prompt reply! I greatly appreciate your fabulous work and your code organization is very clear. After rerunning the profiling, the previous error has disappeared, and I am very grateful for your assistance. 

However, I encountered an error related to the "SparseCUDA backend" when running dlrm_fae.py. I have searched for a solution to this issue but it is still unsolved. Have you encountered this problem before?

Here are the detail information(It happens when switch to train the hot input):

Traceback (most recent call last):
  File "dlrm_fae.py", line 1448, in <module>
    E.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/_functions.py", line 34, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
NotImplementedError: Could not run 'aten::view' with arguments from the 'SparseCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::view' is only available for these backends: [CPU, CUDA, Meta, QuantizedCPU, QuantizedCUDA, MkldnnCPU, NestedTensorCPU, NestedTensorCUDA

**Comment by madnan92** [comment]
Hi @Wangzesonga
It seems that there are some missing functions in your Pytorch version.
As the above issue is resolved, I am closing this issue.
You can open a new issue if you get some issues after fixing your environment.
